import type {
  ScenarioAssumptions,
  ScenarioAsset,
  ScenarioClientComputed,
  ScenarioLiability,
  ScenarioMember,
  ScenarioMeta,
} from "../../store/scenarioStore";
import type { ScenarioEvent, ScenarioEventDraft } from "../scenarioV2/events";

export type ValidationIssue = {
  code:
    | "required"
    | "invalid-month"
    | "invalid-id"
    | "invalid-currency"
    | "invalid-number"
    | "inconsistent-mortgage";
  field: string;
  message: string;
};

export type AutoGeneratedSource =
  | "manual"
  | "auto:property"
  | "auto:mortgage"
  | "auto:rental";

export type AutoGeneratedItem<T extends Record<string, unknown> = Record<string, unknown>> = T & {
  source: AutoGeneratedSource;
  overridableFields?: Array<keyof T & string>;
  lockedFields?: Array<keyof T & string>;
};

export type ScenarioDraftV3 = {
  profile?: {
    baseCurrency?: string;
    startMonth?: string;
    horizonMonths?: number;
  };
  income?: {
    salaryMonthly?: number;
    salaryGrowthRatePct?: number;
  };
  assumptions?: Partial<ScenarioAssumptions>;
  members?: ScenarioMember[];
  assets?: Array<ScenarioAsset | AutoGeneratedItem<ScenarioAsset>>;
  liabilities?: Array<ScenarioLiability | AutoGeneratedItem<ScenarioLiability>>;
  events?: Array<ScenarioEvent | ScenarioEventDraft>;
  meta?: Partial<ScenarioMeta>;
  clientComputed?: Partial<ScenarioClientComputed>;
  baseCurrency?: string;
};

export type ScenarioDraft = ScenarioDraftV3;

export type ScenarioCreatePayload = {
  assumptions: ScenarioAssumptions;
  members: ScenarioMember[];
  assets: ScenarioAsset[];
  liabilities: ScenarioLiability[];
  events: ScenarioEvent[];
  meta: ScenarioMeta;
  clientComputed: ScenarioClientComputed;
  baseCurrency: string;
  validationIssues: ValidationIssue[];
};
