import { defaultCurrency } from "../../../lib/i18n";
import { isValidMonthKey } from "../../utils/monthKey";
import type {
  AutoGeneratedItem,
  ScenarioDraftV3,
  ValidationIssue,
} from "./types";

const MONTH_FIELD_PATTERN = /Month$/;

const normalizeStringId = (
  value: string | undefined,
  fallback: string,
  field: string,
  issues: ValidationIssue[]
) => {
  const trimmed = value?.trim();
  if (!trimmed) {
    issues.push({ code: "invalid-id", field, message: `${field} is required.` });
    return fallback;
  }
  return trimmed;
};

export const normalizeCurrencyCode = (
  currency: string | undefined,
  issues: ValidationIssue[],
  field = "baseCurrency",
  requirePresence = false
) => {
  const normalized = currency?.trim().toUpperCase();
  if (!normalized) {
    if (requirePresence) {
      issues.push({ code: "required", field, message: `${field} is required.` });
    }
    return defaultCurrency;
  }
  if (!/^[A-Z]{3}$/.test(normalized)) {
    issues.push({ code: "invalid-currency", field, message: `${field} must be an ISO 4217 currency code.` });
    return defaultCurrency;
  }
  return normalized;
};

const normalizeMonthOrNull = (
  month: string | null | undefined,
  field: string,
  issues: ValidationIssue[]
): string | null => {
  if (!month) {
    return null;
  }
  if (!isValidMonthKey(month)) {
    issues.push({ code: "invalid-month", field, message: `${field} has invalid month ${month}.` });
    return null;
  }
  return month;
};

const validateRequiredNumeric = (
  value: number | undefined,
  min: number,
  field: string,
  issues: ValidationIssue[]
) => {
  if (value === undefined || value === null) {
    issues.push({ code: "required", field, message: `${field} is required.` });
    return;
  }
  if (!Number.isFinite(value) || value < min) {
    issues.push({ code: "invalid-number", field, message: `${field} must be >= ${min}.` });
  }
};

const validateMonthFields = (
  draft: ScenarioDraftV3,
  issues: ValidationIssue[],
  requireV3Fields: boolean
) => {
  const profileStartMonth = normalizeMonthOrNull(draft.profile?.startMonth, "profile.startMonth", issues);
  normalizeMonthOrNull(draft.assumptions?.baseMonth, "assumptions.baseMonth", issues);

  if (requireV3Fields) {
    if (!profileStartMonth) {
      issues.push({ code: "required", field: "profile.startMonth", message: "profile.startMonth is required." });
    }
  }

  (draft.members ?? []).forEach((member, index) => {
    if (member.birthMonth) {
      normalizeMonthOrNull(member.birthMonth, `members.${index}.birthMonth`, issues);
    }
  });

  const collections = [
    { key: "assets", items: draft.assets ?? [] },
    { key: "liabilities", items: draft.liabilities ?? [] },
    { key: "events", items: draft.events ?? [] },
  ] as const;

  collections.forEach(({ key, items }) => {
    items.forEach((item, index) => {
      Object.entries(item as Record<string, unknown>).forEach(([field, value]) => {
        if (!MONTH_FIELD_PATTERN.test(field) || typeof value !== "string") {
          return;
        }
        normalizeMonthOrNull(value, `${key}.${index}.${field}`, issues);
      });
    });
  });
};

const validateMortgageConsistency = (
  draft: ScenarioDraftV3,
  issues: ValidationIssue[],
  requireV3Fields: boolean
) => {
  if (!requireV3Fields) {
    return;
  }
  (draft.liabilities ?? []).forEach((liability, index) => {
    if (liability.kind !== "mortgage") {
      return;
    }
    const hasRate = liability.annualInterestRatePct !== undefined;
    const hasTerm = liability.termYears !== undefined;
    if (hasRate !== hasTerm) {
      issues.push({
        code: "inconsistent-mortgage",
        field: `liabilities.${index}`,
        message: "Mortgage annualInterestRatePct and termYears must both be provided.",
      });
    }
  });
};

const normalizeAutoGeneratedItem = <T extends Record<string, unknown>>(
  item: T | AutoGeneratedItem<T>
): T => ({ ...item });

export const validateScenarioDraftV3 = (draft: ScenarioDraftV3) => {
  const issues: ValidationIssue[] = [];

  const requireV3Fields = Boolean(draft.profile || draft.income);

  if (requireV3Fields) {
    validateRequiredNumeric(draft.profile?.horizonMonths, 1, "profile.horizonMonths", issues);
    validateRequiredNumeric(draft.income?.salaryMonthly, 0, "income.salaryMonthly", issues);
  }

  validateMonthFields(draft, issues, requireV3Fields);
  validateMortgageConsistency(draft, issues, requireV3Fields);

  const members = (draft.members ?? []).map((member, index) => ({
    ...member,
    id: normalizeStringId(member.id, `member-${index + 1}`, `members.${index}.id`, issues),
  }));

  const assets = (draft.assets ?? []).map((asset, index) => {
    const normalized = normalizeAutoGeneratedItem(asset);
    return {
      ...normalized,
      id: normalizeStringId(normalized.id as string | undefined, `asset-${index + 1}`, `assets.${index}.id`, issues),
      currency: normalizeCurrencyCode(normalized.currency as string | undefined, issues, `assets.${index}.currency`),
    };
  });

  const liabilities = (draft.liabilities ?? []).map((liability, index) => {
    const normalized = normalizeAutoGeneratedItem(liability);
    return {
      ...normalized,
      id: normalizeStringId(
        normalized.id as string | undefined,
        `liability-${index + 1}`,
        `liabilities.${index}.id`,
        issues
      ),
    };
  });

  const events = (draft.events ?? []).map((event, index) => ({
    ...event,
    id: normalizeStringId(event.id, `event-${index + 1}`, `events.${index}.id`, issues),
  }));

  const baseCurrency = requireV3Fields
    ? normalizeCurrencyCode(
        draft.profile?.baseCurrency ?? draft.baseCurrency,
        issues,
        "profile.baseCurrency",
        true
      )
    : normalizeCurrencyCode(
        draft.profile?.baseCurrency ?? draft.baseCurrency ?? defaultCurrency,
        issues,
        "profile.baseCurrency"
      );

  return {
    normalizedDraft: {
      ...draft,
      members,
      assets,
      liabilities,
      events,
      baseCurrency,
    },
    issues,
  };
};

export const validateAndNormalizeScenarioDraft = validateScenarioDraftV3;
