import type { ScenarioEvent } from "../../scenarioV2/events";

type RuleMeta = {
  originAssetId?: string;
  generatedByRule?: string;
};

type EventWithOverride = ScenarioEvent & {
  metadata?: RuleMeta;
  override?: {
    amount?: number;
    startMonth?: string;
  };
};

const isCashflow = (event: ScenarioEvent): event is EventWithOverride & { type: "cashflow" } =>
  event.type === "cashflow";

const getMeta = (event: EventWithOverride): RuleMeta => event.metadata ?? {};

const isAutoGenerated = (event: EventWithOverride) => event.id.startsWith("auto:");

const buildDedupeKey = (event: EventWithOverride & { type: "cashflow" }) => {
  const meta = getMeta(event);
  return [event.startMonth ?? "", event.kind, meta.originAssetId ?? "", meta.generatedByRule ?? ""].join("|");
};

export const dedupeGeneratedAndManual = (events: EventWithOverride[]): EventWithOverride[] => {
  const generatedByKey = new Map<string, EventWithOverride & { type: "cashflow" }>();
  const manualByKey = new Map<string, EventWithOverride & { type: "cashflow" }>();

  events.forEach((event) => {
    if (!isCashflow(event)) {
      return;
    }

    const key = buildDedupeKey(event);
    if (isAutoGenerated(event)) {
      generatedByKey.set(key, event);
      return;
    }

    manualByKey.set(key, event);
  });

  manualByKey.forEach((manualEvent, key) => {
    const generatedEvent = generatedByKey.get(key);
    if (!generatedEvent) {
      return;
    }

    generatedEvent.override = {
      ...(generatedEvent.override ?? {}),
      ...(manualEvent.amount !== generatedEvent.amount ? { amount: manualEvent.amount } : {}),
      ...(manualEvent.startMonth !== generatedEvent.startMonth
        ? { startMonth: manualEvent.startMonth }
        : {}),
    };
  });

  return events.filter((event) => {
    if (!isCashflow(event) || isAutoGenerated(event)) {
      return true;
    }

    const generatedEvent = generatedByKey.get(buildDedupeKey(event));
    return !generatedEvent;
  });
};
