import type { ScenarioLiability } from "../../../store/scenarioStore";
import type { ScenarioEvent } from "../../scenarioV2/events";
import type { AutoGeneratedItem, GeneratedItemMetadata, ScenarioDraftV3 } from "../types";

type PropertyLikeAsset = {
  id: string;
  assetType?: string;
  kind?: string;
  startMonth?: string;
  usage?: string;
  rentMonthly?: number;
  mortgagePrincipalOutstanding?: number;
  mortgageAnnualInterestRatePct?: number;
  mortgageTermYears?: number;
  mortgageTermMonths?: number;
  mortgagePaymentMonthly?: number;
  holdingCostMonthly?: number;
};

type DraftEvent = ScenarioEvent & {
  metadata?: GeneratedItemMetadata;
  override?: {
    amount?: number;
    startMonth?: string;
  };
};

const toFiniteNumber = (value: unknown): number | undefined => {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    return undefined;
  }
  return value;
};

const buildMonthlyPayment = (principal: number, annualRatePct: number, totalMonths: number) => {
  const monthlyRate = annualRatePct / 1200;
  if (monthlyRate <= 0) {
    return principal / totalMonths;
  }
  const growth = (1 + monthlyRate) ** totalMonths;
  return (principal * monthlyRate * growth) / (growth - 1);
};

const buildMetadata = (originAssetId: string, generatedByRule: string): GeneratedItemMetadata => ({
  originAssetId,
  generatedByRule,
  editableFields: ["amount", "startMonth"],
});

export const deriveFromProperty = (draft: ScenarioDraftV3) => {
  const events: DraftEvent[] = [];
  const liabilities: Array<ScenarioLiability | AutoGeneratedItem<ScenarioLiability>> = [];

  const propertyAssets = (draft.assets ?? []) as PropertyLikeAsset[];

  propertyAssets.forEach((asset) => {
    const isPropertyAsset = asset.assetType
      ? asset.assetType === "property"
      : asset.kind === "home" || asset.kind === "property";

    if (!asset?.id || !isPropertyAsset) {
      return;
    }

    const startMonth = asset.startMonth ?? draft.profile?.startMonth;
    if (!startMonth) {
      return;
    }

    if (asset.usage === "rent") {
      events.push({
        id: `auto:${asset.id}:rent-income`,
        type: "cashflow",
        kind: "income",
        cadence: "monthly",
        amount: toFiniteNumber(asset.rentMonthly) ?? 0,
        startMonth,
        metadata: buildMetadata(asset.id, "property.rent.income.v1"),
      });
    }

    const principal = toFiniteNumber(asset.mortgagePrincipalOutstanding);
    const annualRate = toFiniteNumber(asset.mortgageAnnualInterestRatePct);
    const termYears = toFiniteNumber(asset.mortgageTermYears);
    const termMonths = toFiniteNumber(asset.mortgageTermMonths);
    const totalMonths = termMonths !== undefined ? termMonths + (termYears ?? 0) * 12 : termYears !== undefined ? termYears * 12 : undefined;

    if (principal !== undefined) {
      liabilities.push({
        id: `auto:${asset.id}:mortgage-liability`,
        kind: "mortgage",
        principalOutstanding: principal,
        annualInterestRatePct: annualRate,
        termYears: totalMonths !== undefined ? totalMonths / 12 : undefined,
        startMonth,
        metadata: buildMetadata(asset.id, "property.mortgage.liability.v1"),
      });
    }

    if (principal !== undefined && annualRate !== undefined && totalMonths !== undefined) {
      const amortizationAmount =
        toFiniteNumber(asset.mortgagePaymentMonthly) ?? buildMonthlyPayment(principal, annualRate, totalMonths);
      events.push({
        id: `auto:${asset.id}:mortgage-payment`,
        type: "cashflow",
        kind: "expense",
        cadence: "monthly",
        amount: amortizationAmount,
        startMonth,
        metadata: buildMetadata(asset.id, "property.mortgage.payment.v1"),
      });
    }

    events.push({
      id: `auto:${asset.id}:holding-cost`,
      type: "cashflow",
      kind: "expense",
      cadence: "monthly",
      amount: toFiniteNumber(asset.holdingCostMonthly) ?? 0,
      startMonth,
      metadata: buildMetadata(asset.id, "property.holding-cost.v1"),
    });
  });

  return { events, liabilities };
};
