import { Badge } from "@mantine/core";
import { useTranslations } from "next-intl";

type Props = {
  rule?: string;
};

const resolveRuleLabel = (
  rule: string | undefined,
  t: ReturnType<typeof useTranslations>
) => {
  if (!rule) {
    return t("source.system");
  }

  if (rule.includes("mortgage.payment")) {
    return t("source.mortgagePayment");
  }
  if (rule.includes("holding-cost")) {
    return t("source.holdingCost");
  }
  if (rule.includes("rent.income")) {
    return t("source.rentIncome");
  }
  return t("source.system");
};

export default function AutoGeneratedBadge({ rule }: Props) {
  const t = useTranslations("onboarding.generatedCashflow");
  return (
    <Badge size="xs" variant="light" color="blue">
      {t("badge", { source: resolveRuleLabel(rule, t) })}
    </Badge>
  );
}
