import { Alert, Button, Group, NumberInput, Stack, Switch, Table, Text } from "@mantine/core";
import { useTranslations } from "next-intl";
import AutoGeneratedBadge from "./AutoGeneratedBadge";

type Props = {
  id: string;
  rule?: string;
  baseAmount: number;
  overrideAmount?: number;
  disabled?: boolean;
  onOverrideAmount: (value: number) => void;
  onRestoreSuggested: () => void;
  onToggleDisabled: (value: boolean) => void;
};

export default function GeneratedCashflowRow({
  id,
  rule,
  baseAmount,
  overrideAmount,
  disabled,
  onOverrideAmount,
  onRestoreSuggested,
  onToggleDisabled,
}: Props) {
  const t = useTranslations("onboarding.generatedCashflow");
  const hasOverride = typeof overrideAmount === "number";

  return (
    <Table.Tr key={id}>
      <Table.Td>
        <Stack gap={4}>
          <AutoGeneratedBadge rule={rule} />
          <Text size="xs" c="dimmed">
            {rule ?? t("ruleFallback")}
          </Text>
        </Stack>
      </Table.Td>
      <Table.Td>
        <Text size="sm">{baseAmount.toLocaleString()}</Text>
      </Table.Td>
      <Table.Td>
        <Stack gap="xs">
          <Group align="end" gap="xs" wrap="nowrap">
            <NumberInput
              value={hasOverride ? overrideAmount : baseAmount}
              disabled={Boolean(disabled)}
              onChange={(value) => onOverrideAmount(typeof value === "number" ? value : 0)}
            />
            <Button
              size="xs"
              variant="subtle"
              disabled={!hasOverride && !disabled}
              onClick={onRestoreSuggested}
            >
              {t("restoreSuggested")}
            </Button>
          </Group>
          <Switch
            checked={!disabled}
            label={t("autoEnabled")}
            onChange={(event) => onToggleDisabled(!event.currentTarget.checked)}
          />
          {disabled ? (
            <Alert color="yellow">
              {t("disableRisk")}
            </Alert>
          ) : null}
        </Stack>
      </Table.Td>
    </Table.Tr>
  );
}
